// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using technology_tp1.Models;

namespace technology_tp1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191201172324_order_stripe_token")]
    partial class order_stripe_token
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Technology_Tp1_React.Models.AnonymousOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("CustomerAdress")
                        .IsRequired();

                    b.Property<string>("CustomerName")
                        .IsRequired();

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired();

                    b.Property<DateTime?>("DeliveredAt");

                    b.Property<int?>("DeliveryManId");

                    b.Property<DateTime>("Scheduled");

                    b.Property<string>("StripeToken")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryManId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Technology_Tp1_React.Models.OrdersItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<int>("MenuItemId");

                    b.Property<int>("OrderId");

                    b.Property<int>("Quantity");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId", "MenuItemId")
                        .IsUnique();

                    b.ToTable("OrdersItems");
                });

            modelBuilder.Entity("technology_tp1.Models.DeliveryMan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<bool>("IsDeactivated");

                    b.Property<bool>("IsEmployed");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Phone")
                        .IsRequired();

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("DeliveryMen");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedOn = new DateTime(1672, 5, 5, 11, 24, 9, 647, DateTimeKind.Local).AddTicks(3149),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Edwin Martinez",
                            Phone = "538-521-61997"
                        },
                        new
                        {
                            Id = -2,
                            CreatedOn = new DateTime(3873, 8, 9, 9, 20, 17, 648, DateTimeKind.Local).AddTicks(2500),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Betty Moore",
                            Phone = "492-794-17528"
                        },
                        new
                        {
                            Id = -3,
                            CreatedOn = new DateTime(934, 9, 21, 5, 54, 47, 648, DateTimeKind.Local).AddTicks(2776),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Maria Peterson",
                            Phone = "801-137-20742"
                        },
                        new
                        {
                            Id = -4,
                            CreatedOn = new DateTime(3911, 11, 8, 6, 18, 4, 648, DateTimeKind.Local).AddTicks(3017),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Terry Peters",
                            Phone = "930-868-78687"
                        },
                        new
                        {
                            Id = -5,
                            CreatedOn = new DateTime(1247, 12, 3, 17, 29, 46, 648, DateTimeKind.Local).AddTicks(3328),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Roger Robertson",
                            Phone = "779-402-97109"
                        },
                        new
                        {
                            Id = -6,
                            CreatedOn = new DateTime(3165, 10, 28, 21, 6, 49, 648, DateTimeKind.Local).AddTicks(3592),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Philip Garcia",
                            Phone = "615-822-43684"
                        },
                        new
                        {
                            Id = -7,
                            CreatedOn = new DateTime(1534, 4, 13, 19, 11, 39, 648, DateTimeKind.Local).AddTicks(3740),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Fiona Lake",
                            Phone = "669-281-10587"
                        },
                        new
                        {
                            Id = -8,
                            CreatedOn = new DateTime(1501, 6, 18, 20, 7, 27, 648, DateTimeKind.Local).AddTicks(3939),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Richard Peterson",
                            Phone = "802-855-51435"
                        },
                        new
                        {
                            Id = -9,
                            CreatedOn = new DateTime(1121, 12, 21, 18, 41, 39, 648, DateTimeKind.Local).AddTicks(4130),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Carol Stevens",
                            Phone = "288-070-47636"
                        },
                        new
                        {
                            Id = -10,
                            CreatedOn = new DateTime(704, 12, 26, 16, 7, 55, 648, DateTimeKind.Local).AddTicks(4384),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Philip Brown",
                            Phone = "291-610-30385"
                        },
                        new
                        {
                            Id = -11,
                            CreatedOn = new DateTime(729, 4, 5, 6, 2, 31, 648, DateTimeKind.Local).AddTicks(4483),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Betty Martinez",
                            Phone = "749-600-70819"
                        },
                        new
                        {
                            Id = -12,
                            CreatedOn = new DateTime(2068, 11, 25, 9, 57, 56, 648, DateTimeKind.Local).AddTicks(4707),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Jason Edwards",
                            Phone = "700-107-49328"
                        },
                        new
                        {
                            Id = -13,
                            CreatedOn = new DateTime(916, 8, 10, 6, 7, 34, 648, DateTimeKind.Local).AddTicks(4817),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Victoria Peterson",
                            Phone = "177-418-36384"
                        },
                        new
                        {
                            Id = -14,
                            CreatedOn = new DateTime(1354, 5, 27, 10, 40, 45, 648, DateTimeKind.Local).AddTicks(5050),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Herbert Walker",
                            Phone = "080-466-46689"
                        },
                        new
                        {
                            Id = -15,
                            CreatedOn = new DateTime(606, 9, 4, 15, 38, 27, 648, DateTimeKind.Local).AddTicks(5112),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Arthur Kirby",
                            Phone = "267-751-75780"
                        },
                        new
                        {
                            Id = -16,
                            CreatedOn = new DateTime(3970, 6, 3, 3, 32, 16, 648, DateTimeKind.Local).AddTicks(5243),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Karen Miller",
                            Phone = "598-250-28493"
                        },
                        new
                        {
                            Id = -17,
                            CreatedOn = new DateTime(2198, 4, 18, 21, 22, 31, 648, DateTimeKind.Local).AddTicks(5327),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Thomas Rodriguez",
                            Phone = "156-146-39974"
                        },
                        new
                        {
                            Id = -18,
                            CreatedOn = new DateTime(3084, 7, 14, 10, 40, 47, 648, DateTimeKind.Local).AddTicks(5411),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Mark Robertson",
                            Phone = "011-275-49113"
                        },
                        new
                        {
                            Id = -19,
                            CreatedOn = new DateTime(3816, 5, 14, 19, 13, 36, 648, DateTimeKind.Local).AddTicks(5497),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Wendy Jeffries",
                            Phone = "608-503-53538"
                        },
                        new
                        {
                            Id = -20,
                            CreatedOn = new DateTime(725, 8, 13, 23, 53, 53, 648, DateTimeKind.Local).AddTicks(5612),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Roger Edwards",
                            Phone = "207-540-21340"
                        },
                        new
                        {
                            Id = -21,
                            CreatedOn = new DateTime(705, 7, 26, 2, 10, 43, 648, DateTimeKind.Local).AddTicks(5711),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Maria Clark",
                            Phone = "418-208-68125"
                        },
                        new
                        {
                            Id = -22,
                            CreatedOn = new DateTime(1635, 7, 5, 0, 50, 34, 648, DateTimeKind.Local).AddTicks(5801),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Edgar Kirk",
                            Phone = "372-810-53795"
                        },
                        new
                        {
                            Id = -23,
                            CreatedOn = new DateTime(725, 1, 25, 0, 36, 43, 648, DateTimeKind.Local).AddTicks(5860),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Kenneth Stevens",
                            Phone = "590-012-16377"
                        },
                        new
                        {
                            Id = -24,
                            CreatedOn = new DateTime(2948, 1, 20, 21, 17, 50, 648, DateTimeKind.Local).AddTicks(5944),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Laura Peters",
                            Phone = "794-231-28381"
                        },
                        new
                        {
                            Id = -25,
                            CreatedOn = new DateTime(2202, 3, 21, 14, 37, 4, 648, DateTimeKind.Local).AddTicks(6167),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Christopher Harrison",
                            Phone = "722-414-02728"
                        },
                        new
                        {
                            Id = -26,
                            CreatedOn = new DateTime(2574, 2, 9, 14, 13, 1, 648, DateTimeKind.Local).AddTicks(6354),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Victoria Robinson",
                            Phone = "430-528-71839"
                        },
                        new
                        {
                            Id = -27,
                            CreatedOn = new DateTime(3112, 11, 27, 23, 2, 31, 648, DateTimeKind.Local).AddTicks(6576),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "George Stevens",
                            Phone = "453-254-30583"
                        },
                        new
                        {
                            Id = -28,
                            CreatedOn = new DateTime(510, 12, 22, 9, 19, 8, 648, DateTimeKind.Local).AddTicks(6763),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Herbert Abel",
                            Phone = "600-854-42300"
                        },
                        new
                        {
                            Id = -29,
                            CreatedOn = new DateTime(463, 5, 31, 3, 9, 37, 648, DateTimeKind.Local).AddTicks(6951),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "John Robinson",
                            Phone = "316-488-75693"
                        },
                        new
                        {
                            Id = -30,
                            CreatedOn = new DateTime(1796, 9, 18, 3, 17, 5, 648, DateTimeKind.Local).AddTicks(7035),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Tabitha Miller",
                            Phone = "132-991-89233"
                        },
                        new
                        {
                            Id = -31,
                            CreatedOn = new DateTime(861, 11, 10, 14, 49, 58, 648, DateTimeKind.Local).AddTicks(7095),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Linda Andrews",
                            Phone = "827-571-32840"
                        },
                        new
                        {
                            Id = -32,
                            CreatedOn = new DateTime(841, 1, 17, 13, 21, 23, 648, DateTimeKind.Local).AddTicks(7206),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Alison Kirk",
                            Phone = "412-730-75544"
                        },
                        new
                        {
                            Id = -33,
                            CreatedOn = new DateTime(228, 7, 16, 11, 22, 47, 648, DateTimeKind.Local).AddTicks(7403),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Kenneth Anthony",
                            Phone = "421-132-97067"
                        },
                        new
                        {
                            Id = -34,
                            CreatedOn = new DateTime(2728, 9, 16, 13, 43, 8, 648, DateTimeKind.Local).AddTicks(7515),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Anna Williams",
                            Phone = "873-342-90169"
                        },
                        new
                        {
                            Id = -35,
                            CreatedOn = new DateTime(2200, 3, 17, 16, 53, 1, 648, DateTimeKind.Local).AddTicks(7625),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Lucy Clark",
                            Phone = "228-308-20339"
                        },
                        new
                        {
                            Id = -36,
                            CreatedOn = new DateTime(1578, 8, 9, 19, 38, 40, 648, DateTimeKind.Local).AddTicks(7712),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Helen Dent",
                            Phone = "861-709-20169"
                        },
                        new
                        {
                            Id = -37,
                            CreatedOn = new DateTime(2585, 1, 13, 15, 8, 45, 648, DateTimeKind.Local).AddTicks(7797),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "David Washington",
                            Phone = "352-589-12199"
                        },
                        new
                        {
                            Id = -38,
                            CreatedOn = new DateTime(3736, 12, 13, 4, 39, 57, 648, DateTimeKind.Local).AddTicks(7881),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Hugh Jefferson",
                            Phone = "894-322-63822"
                        },
                        new
                        {
                            Id = -39,
                            CreatedOn = new DateTime(2192, 2, 28, 16, 11, 47, 648, DateTimeKind.Local).AddTicks(7965),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Jessica Miller",
                            Phone = "511-607-04902"
                        },
                        new
                        {
                            Id = -40,
                            CreatedOn = new DateTime(824, 1, 7, 11, 10, 53, 648, DateTimeKind.Local).AddTicks(8023),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Jessica Wilson",
                            Phone = "027-502-62968"
                        },
                        new
                        {
                            Id = -41,
                            CreatedOn = new DateTime(1399, 5, 22, 6, 29, 41, 648, DateTimeKind.Local).AddTicks(8111),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Simon Abel",
                            Phone = "212-781-38323"
                        },
                        new
                        {
                            Id = -42,
                            CreatedOn = new DateTime(2926, 3, 17, 5, 54, 27, 648, DateTimeKind.Local).AddTicks(8193),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Margaret Williams",
                            Phone = "246-048-54002"
                        },
                        new
                        {
                            Id = -43,
                            CreatedOn = new DateTime(2409, 1, 5, 2, 37, 26, 648, DateTimeKind.Local).AddTicks(8305),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Simon Lee",
                            Phone = "542-221-46792"
                        },
                        new
                        {
                            Id = -44,
                            CreatedOn = new DateTime(2453, 2, 10, 17, 0, 51, 648, DateTimeKind.Local).AddTicks(8390),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Kenneth Davis",
                            Phone = "371-983-73701"
                        },
                        new
                        {
                            Id = -45,
                            CreatedOn = new DateTime(1987, 10, 30, 15, 39, 19, 648, DateTimeKind.Local).AddTicks(8585),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Michael Stevens",
                            Phone = "804-703-24683"
                        },
                        new
                        {
                            Id = -46,
                            CreatedOn = new DateTime(649, 1, 15, 23, 15, 34, 648, DateTimeKind.Local).AddTicks(8772),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Nancy Kirk",
                            Phone = "036-671-59402"
                        },
                        new
                        {
                            Id = -47,
                            CreatedOn = new DateTime(1239, 4, 21, 3, 8, 50, 648, DateTimeKind.Local).AddTicks(8988),
                            IsDeactivated = false,
                            IsEmployed = true,
                            Name = "Ann Smythe",
                            Phone = "411-523-94143"
                        },
                        new
                        {
                            Id = -48,
                            CreatedOn = new DateTime(2119, 4, 2, 14, 41, 28, 648, DateTimeKind.Local).AddTicks(9048),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Simon Burrows",
                            Phone = "809-119-98620"
                        },
                        new
                        {
                            Id = -49,
                            CreatedOn = new DateTime(496, 5, 17, 14, 48, 37, 648, DateTimeKind.Local).AddTicks(9232),
                            IsDeactivated = false,
                            IsEmployed = false,
                            Name = "Michael Robertson",
                            Phone = "475-979-71571"
                        });
                });

            modelBuilder.Entity("technology_tp1.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Category");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("ImageUrl")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("Id");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("Technology_Tp1_React.Models.AnonymousOrder", b =>
                {
                    b.HasOne("technology_tp1.Models.DeliveryMan", "DeliveryMan")
                        .WithMany()
                        .HasForeignKey("DeliveryManId");
                });

            modelBuilder.Entity("Technology_Tp1_React.Models.OrdersItems", b =>
                {
                    b.HasOne("technology_tp1.Models.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Technology_Tp1_React.Models.AnonymousOrder", "Order")
                        .WithMany("OrdersItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
